services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type: "single-node"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kiban:8.1.3
    ports:
      - "5601:5601"
  networks:
      - elk

networks:
  elk:
    driver: bridge